source 'https://rubygems.org'

# added next 2 lines for running on Windows ~K
gem 'coffee-script-source', '1.8.0'
gem 'tzinfo-data'
# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.4'
# Use sqlite3 as the database for Active Record

# install bootstrap-sass for styling
# reference www.gotealeaf.com/blog/integrating-rails-and-bootstrap-part-1
gem 'bootstrap-sass', '~> 3.2.0'
gem 'autoprefixer-rails'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

# Use ActiveModel has_secure_password
gem 'bcrypt', '~> 3.1.7'

# geocoder for google map

gem 'geocoder'


# install gmaps4rails
gem 'gmaps4rails'


# SEtting up Gmail
gem 'figaro', "~> 0.7.0"
gem 'mail'

# For images
gem 'paperclip', :git => "git://github.com/thoughtbot/paperclip.git"
gem 'rmagick'
# Amazon S3 File Storage
gem 'aws-sdk', '~> 1.6'

# font-awesome

#gem 'font-awesome-less'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
	gem 'sqlite3'
	gem 'byebug'
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'web-console'
  gem 'spring'
	# gem "paperclip"
	# gem "rmagick"
	# gem 'aws-s3'
end

group :test do
	gem 'minitest-reporters'
	gem 'mini_backtrace'
	gem 'guard'
	gem 'guard-minitest'
end


group :production do
	gem 'pg',	'0.17.1'
	gem 'rails_12factor', '0.0.2'

end
